export const BlogPosts = [
    {
      id: 1,
      slug: "future-of-digital-marketing",
      title: "The Future of Digital Marketing",
      excerpt: "Explore the latest trends shaping the digital marketing landscape in 2025 and beyond.",
      category: "Marketing",
      image: "/images/Blog1.avif",
      author: "Muhammad Abdullah Rasheed",
      date: "20-10-2024",
      gradient: "from-[#4646ff] to-[#6366F1]",
      color: "#4646ff",
      content: "Full content of the blog post goes here...",
    },
    {
      id: 2,
      slug: "mastering-ux-design",
      title: "Mastering UX Design",
      excerpt: "Learn the key principles of user experience design that can transform your digital products.",
      category: "Design",
      image: "/images/Blog2.avif",
      gradient: "from-[#4646ff] to-[#6366F1]",
      color: "#4646ff",
      author: "Muhammad Abdullah Rasheed",
      date: "2024-02-20" ,
      content: "Full content of the blog post goes here...",
    },
    {
      id: 3,
      slug: "ai-in-web-development",
      title: "AI in Web Development",
      excerpt: "Discover how artificial intelligence is revolutionizing the way we build and maintain websites.",
      category: "Technology",
      image: "/images/Blog3.avif",
      gradient: "from-[#4646ff] to-[#6366F1]",
      color: "#4646ff",
      content: "Full content of the blog post goes here...",
    },
    {
      id: 4,
      slug: "power-of-content-strategy",
      title: "The Power of Content Strategy",
      excerpt: "Uncover the secrets to creating a content strategy that drives engagement and conversions.",
      category: "Content",
      image: "/images/Blog4.avif",
      gradient: "from-[#4646ff] to-[#6366F1]",
      color: "#4646ff",
      content: "Full content of the blog post goes here...",
    },
    {
      id: 5,
      slug: "responsive-design-best-practices",
      title: "Responsive Design Best Practices",
      excerpt: "Stay ahead of the curve with these cutting-edge responsive design techniques for 2025.",
      category: "Design",
      image: "/images/Blog5.avif",
      gradient: "from-[#4646ff] to-[#6366F1]",
      color: "#4646ff",
      content: "Full content of the blog post goes here...",
    },
    {
      id: 6,
      slug: "seo-strategies-for-voice-search",
      title: "SEO Strategies for Voice Search",
      excerpt: "Optimize your digital presence for the growing trend of voice-activated search queries.",
      category: "Marketing",
      image: "/images/Blog6.avif",
      gradient: "from-[#4646ff] to-[#6366F1]",
      color: "#4646ff",
      content: "Full content of the blog post goes here...",
    },
  ]
  
  